//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Gestioname.Model", "FK_Cuentas_Clientes", "Clientes", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Gestioname.Infrastructure.Model.Clientes), "Cuentas", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gestioname.Infrastructure.Model.Cuentas))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Gestioname.Model", "FK_Transacciones_Cuentas", "Cuentas", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gestioname.Infrastructure.Model.Cuentas), "Transacciones", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gestioname.Infrastructure.Model.Transacciones))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Gestioname.Model", "FK_Pagos_Transacciones", "Transacciones", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gestioname.Infrastructure.Model.Transacciones), "Pagos", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gestioname.Infrastructure.Model.Pagos))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Gestioname.Model", "FK_Transacciones_TiposTransacciones", "TiposTransacciones", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gestioname.Infrastructure.Model.TiposTransacciones), "Transacciones", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gestioname.Infrastructure.Model.Transacciones))]

// Original file name:
// Generation date: 29/12/2008 11:08:30 a.m.
namespace Gestioname.Infrastructure.Model
{
    
    /// <summary>
    /// There are no comments for GestionameDBConnectionString in the schema.
    /// </summary>
    public partial class GestionameDBConnectionString : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new GestionameDBConnectionString object using the connection string found in the 'GestionameDBConnectionString' section of the application configuration file.
        /// </summary>
        public GestionameDBConnectionString() : 
                base("name=GestionameDBConnectionString", "GestionameDBConnectionString")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GestionameDBConnectionString object.
        /// </summary>
        public GestionameDBConnectionString(string connectionString) : 
                base(connectionString, "GestionameDBConnectionString")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GestionameDBConnectionString object.
        /// </summary>
        public GestionameDBConnectionString(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "GestionameDBConnectionString")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Clientes in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Clientes> Clientes
        {
            get
            {
                if ((this._Clientes == null))
                {
                    this._Clientes = base.CreateQuery<Clientes>("[Clientes]");
                }
                return this._Clientes;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Clientes> _Clientes;
        /// <summary>
        /// There are no comments for Configuracion in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Configuracion> Configuracion
        {
            get
            {
                if ((this._Configuracion == null))
                {
                    this._Configuracion = base.CreateQuery<Configuracion>("[Configuracion]");
                }
                return this._Configuracion;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Configuracion> _Configuracion;
        /// <summary>
        /// There are no comments for Cuentas in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Cuentas> Cuentas
        {
            get
            {
                if ((this._Cuentas == null))
                {
                    this._Cuentas = base.CreateQuery<Cuentas>("[Cuentas]");
                }
                return this._Cuentas;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Cuentas> _Cuentas;
        /// <summary>
        /// There are no comments for Pagos in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Pagos> Pagos
        {
            get
            {
                if ((this._Pagos == null))
                {
                    this._Pagos = base.CreateQuery<Pagos>("[Pagos]");
                }
                return this._Pagos;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Pagos> _Pagos;
        /// <summary>
        /// There are no comments for TiposTransacciones in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TiposTransacciones> TiposTransacciones
        {
            get
            {
                if ((this._TiposTransacciones == null))
                {
                    this._TiposTransacciones = base.CreateQuery<TiposTransacciones>("[TiposTransacciones]");
                }
                return this._TiposTransacciones;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TiposTransacciones> _TiposTransacciones;
        /// <summary>
        /// There are no comments for Transacciones in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Transacciones> Transacciones
        {
            get
            {
                if ((this._Transacciones == null))
                {
                    this._Transacciones = base.CreateQuery<Transacciones>("[Transacciones]");
                }
                return this._Transacciones;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Transacciones> _Transacciones;
        /// <summary>
        /// There are no comments for Clientes in the schema.
        /// </summary>
        public void AddToClientes(Clientes clientes)
        {
            base.AddObject("Clientes", clientes);
        }
        /// <summary>
        /// There are no comments for Configuracion in the schema.
        /// </summary>
        public void AddToConfiguracion(Configuracion configuracion)
        {
            base.AddObject("Configuracion", configuracion);
        }
        /// <summary>
        /// There are no comments for Cuentas in the schema.
        /// </summary>
        public void AddToCuentas(Cuentas cuentas)
        {
            base.AddObject("Cuentas", cuentas);
        }
        /// <summary>
        /// There are no comments for Pagos in the schema.
        /// </summary>
        public void AddToPagos(Pagos pagos)
        {
            base.AddObject("Pagos", pagos);
        }
        /// <summary>
        /// There are no comments for TiposTransacciones in the schema.
        /// </summary>
        public void AddToTiposTransacciones(TiposTransacciones tiposTransacciones)
        {
            base.AddObject("TiposTransacciones", tiposTransacciones);
        }
        /// <summary>
        /// There are no comments for Transacciones in the schema.
        /// </summary>
        public void AddToTransacciones(Transacciones transacciones)
        {
            base.AddObject("Transacciones", transacciones);
        }
    }
    /// <summary>
    /// There are no comments for Gestioname.Model.Clientes in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdCliente
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Gestioname.Model", Name="Clientes")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Clientes : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Clientes object.
        /// </summary>
        /// <param name="idCliente">Initial value of IdCliente.</param>
        /// <param name="codigo">Initial value of Codigo.</param>
        public static Clientes CreateClientes(int idCliente, string codigo)
        {
            Clientes clientes = new Clientes();
            clientes.IdCliente = idCliente;
            clientes.Codigo = codigo;
            return clientes;
        }
        /// <summary>
        /// There are no comments for Property IdCliente in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente
        {
            get
            {
                return this._IdCliente;
            }
            set
            {
                this.OnIdClienteChanging(value);
                this.ReportPropertyChanging("IdCliente");
                this._IdCliente = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdCliente");
                this.OnIdClienteChanged();
            }
        }
        private int _IdCliente;
        partial void OnIdClienteChanging(int value);
        partial void OnIdClienteChanged();
        /// <summary>
        /// There are no comments for Property Codigo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this._Codigo;
            }
            set
            {
                this.OnCodigoChanging(value);
                this.ReportPropertyChanging("Codigo");
                this._Codigo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Codigo");
                this.OnCodigoChanged();
            }
        }
        private string _Codigo;
        partial void OnCodigoChanging(string value);
        partial void OnCodigoChanged();
        /// <summary>
        /// There are no comments for Property RazonSocial in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial
        {
            get
            {
                return this._RazonSocial;
            }
            set
            {
                this.OnRazonSocialChanging(value);
                this.ReportPropertyChanging("RazonSocial");
                this._RazonSocial = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("RazonSocial");
                this.OnRazonSocialChanged();
            }
        }
        private string _RazonSocial;
        partial void OnRazonSocialChanging(string value);
        partial void OnRazonSocialChanged();
        /// <summary>
        /// There are no comments for Property Domicilio in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Domicilio
        {
            get
            {
                return this._Domicilio;
            }
            set
            {
                this.OnDomicilioChanging(value);
                this.ReportPropertyChanging("Domicilio");
                this._Domicilio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Domicilio");
                this.OnDomicilioChanged();
            }
        }
        private string _Domicilio;
        partial void OnDomicilioChanging(string value);
        partial void OnDomicilioChanged();
        /// <summary>
        /// There are no comments for Property Localidad in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Localidad
        {
            get
            {
                return this._Localidad;
            }
            set
            {
                this.OnLocalidadChanging(value);
                this.ReportPropertyChanging("Localidad");
                this._Localidad = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Localidad");
                this.OnLocalidadChanged();
            }
        }
        private string _Localidad;
        partial void OnLocalidadChanging(string value);
        partial void OnLocalidadChanged();
        /// <summary>
        /// There are no comments for Property Provincia in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this._Provincia;
            }
            set
            {
                this.OnProvinciaChanging(value);
                this.ReportPropertyChanging("Provincia");
                this._Provincia = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Provincia");
                this.OnProvinciaChanged();
            }
        }
        private string _Provincia;
        partial void OnProvinciaChanging(string value);
        partial void OnProvinciaChanged();
        /// <summary>
        /// There are no comments for Property CUIT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CUIT
        {
            get
            {
                return this._CUIT;
            }
            set
            {
                this.OnCUITChanging(value);
                this.ReportPropertyChanging("CUIT");
                this._CUIT = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CUIT");
                this.OnCUITChanged();
            }
        }
        private string _CUIT;
        partial void OnCUITChanging(string value);
        partial void OnCUITChanged();
        /// <summary>
        /// There are no comments for Cuentas in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Gestioname.Model", "FK_Cuentas_Clientes", "Cuentas")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Cuentas> Cuentas
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Cuentas>("Gestioname.Model.FK_Cuentas_Clientes", "Cuentas");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Cuentas>("Gestioname.Model.FK_Cuentas_Clientes", "Cuentas", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Gestioname.Model.Configuracion in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdConfiguracion
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Gestioname.Model", Name="Configuracion")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Configuracion : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Configuracion object.
        /// </summary>
        /// <param name="idConfiguracion">Initial value of IdConfiguracion.</param>
        /// <param name="clave">Initial value of Clave.</param>
        /// <param name="valor">Initial value of Valor.</param>
        public static Configuracion CreateConfiguracion(int idConfiguracion, string clave, string valor)
        {
            Configuracion configuracion = new Configuracion();
            configuracion.IdConfiguracion = idConfiguracion;
            configuracion.Clave = clave;
            configuracion.Valor = valor;
            return configuracion;
        }
        /// <summary>
        /// There are no comments for Property IdConfiguracion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdConfiguracion
        {
            get
            {
                return this._IdConfiguracion;
            }
            set
            {
                this.OnIdConfiguracionChanging(value);
                this.ReportPropertyChanging("IdConfiguracion");
                this._IdConfiguracion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdConfiguracion");
                this.OnIdConfiguracionChanged();
            }
        }
        private int _IdConfiguracion;
        partial void OnIdConfiguracionChanging(int value);
        partial void OnIdConfiguracionChanged();
        /// <summary>
        /// There are no comments for Property Clave in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave
        {
            get
            {
                return this._Clave;
            }
            set
            {
                this.OnClaveChanging(value);
                this.ReportPropertyChanging("Clave");
                this._Clave = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Clave");
                this.OnClaveChanged();
            }
        }
        private string _Clave;
        partial void OnClaveChanging(string value);
        partial void OnClaveChanged();
        /// <summary>
        /// There are no comments for Property Valor in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor
        {
            get
            {
                return this._Valor;
            }
            set
            {
                this.OnValorChanging(value);
                this.ReportPropertyChanging("Valor");
                this._Valor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Valor");
                this.OnValorChanged();
            }
        }
        private string _Valor;
        partial void OnValorChanging(string value);
        partial void OnValorChanged();
    }
    /// <summary>
    /// There are no comments for Gestioname.Model.Cuentas in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdCuenta
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Gestioname.Model", Name="Cuentas")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Cuentas : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Cuentas object.
        /// </summary>
        /// <param name="idCuenta">Initial value of IdCuenta.</param>
        /// <param name="balance">Initial value of Balance.</param>
        public static Cuentas CreateCuentas(int idCuenta, string balance)
        {
            Cuentas cuentas = new Cuentas();
            cuentas.IdCuenta = idCuenta;
            cuentas.Balance = balance;
            return cuentas;
        }
        /// <summary>
        /// There are no comments for Property IdCuenta in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCuenta
        {
            get
            {
                return this._IdCuenta;
            }
            set
            {
                this.OnIdCuentaChanging(value);
                this.ReportPropertyChanging("IdCuenta");
                this._IdCuenta = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdCuenta");
                this.OnIdCuentaChanged();
            }
        }
        private int _IdCuenta;
        partial void OnIdCuentaChanging(int value);
        partial void OnIdCuentaChanged();
        /// <summary>
        /// There are no comments for Property Balance in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Balance
        {
            get
            {
                return this._Balance;
            }
            set
            {
                this.OnBalanceChanging(value);
                this.ReportPropertyChanging("Balance");
                this._Balance = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Balance");
                this.OnBalanceChanged();
            }
        }
        private string _Balance;
        partial void OnBalanceChanging(string value);
        partial void OnBalanceChanged();
        /// <summary>
        /// There are no comments for Clientes in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Gestioname.Model", "FK_Cuentas_Clientes", "Clientes")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Clientes Clientes
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Clientes>("Gestioname.Model.FK_Cuentas_Clientes", "Clientes").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Clientes>("Gestioname.Model.FK_Cuentas_Clientes", "Clientes").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Clientes in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Clientes> ClientesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Clientes>("Gestioname.Model.FK_Cuentas_Clientes", "Clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Clientes>("Gestioname.Model.FK_Cuentas_Clientes", "Clientes", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Transacciones in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Gestioname.Model", "FK_Transacciones_Cuentas", "Transacciones")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Transacciones> Transacciones
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Transacciones>("Gestioname.Model.FK_Transacciones_Cuentas", "Transacciones");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Transacciones>("Gestioname.Model.FK_Transacciones_Cuentas", "Transacciones", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Gestioname.Model.Pagos in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdPago
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Gestioname.Model", Name="Pagos")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Pagos : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Pagos object.
        /// </summary>
        /// <param name="idPago">Initial value of IdPago.</param>
        /// <param name="tipoPago">Initial value of TipoPago.</param>
        /// <param name="monto">Initial value of Monto.</param>
        public static Pagos CreatePagos(int idPago, string tipoPago, string monto)
        {
            Pagos pagos = new Pagos();
            pagos.IdPago = idPago;
            pagos.TipoPago = tipoPago;
            pagos.Monto = monto;
            return pagos;
        }
        /// <summary>
        /// There are no comments for Property IdPago in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPago
        {
            get
            {
                return this._IdPago;
            }
            set
            {
                this.OnIdPagoChanging(value);
                this.ReportPropertyChanging("IdPago");
                this._IdPago = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdPago");
                this.OnIdPagoChanged();
            }
        }
        private int _IdPago;
        partial void OnIdPagoChanging(int value);
        partial void OnIdPagoChanged();
        /// <summary>
        /// There are no comments for Property TipoPago in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPago
        {
            get
            {
                return this._TipoPago;
            }
            set
            {
                this.OnTipoPagoChanging(value);
                this.ReportPropertyChanging("TipoPago");
                this._TipoPago = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("TipoPago");
                this.OnTipoPagoChanged();
            }
        }
        private string _TipoPago;
        partial void OnTipoPagoChanging(string value);
        partial void OnTipoPagoChanged();
        /// <summary>
        /// There are no comments for Property Monto in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Monto
        {
            get
            {
                return this._Monto;
            }
            set
            {
                this.OnMontoChanging(value);
                this.ReportPropertyChanging("Monto");
                this._Monto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Monto");
                this.OnMontoChanged();
            }
        }
        private string _Monto;
        partial void OnMontoChanging(string value);
        partial void OnMontoChanged();
        /// <summary>
        /// There are no comments for Property NumeroCheque in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCheque
        {
            get
            {
                return this._NumeroCheque;
            }
            set
            {
                this.OnNumeroChequeChanging(value);
                this.ReportPropertyChanging("NumeroCheque");
                this._NumeroCheque = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NumeroCheque");
                this.OnNumeroChequeChanged();
            }
        }
        private string _NumeroCheque;
        partial void OnNumeroChequeChanging(string value);
        partial void OnNumeroChequeChanged();
        /// <summary>
        /// There are no comments for Property Banco in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Banco
        {
            get
            {
                return this._Banco;
            }
            set
            {
                this.OnBancoChanging(value);
                this.ReportPropertyChanging("Banco");
                this._Banco = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Banco");
                this.OnBancoChanged();
            }
        }
        private string _Banco;
        partial void OnBancoChanging(string value);
        partial void OnBancoChanged();
        /// <summary>
        /// There are no comments for Property Fecha in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return this._Fecha;
            }
            set
            {
                this.OnFechaChanging(value);
                this.ReportPropertyChanging("Fecha");
                this._Fecha = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Fecha");
                this.OnFechaChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
        /// <summary>
        /// There are no comments for Transacciones in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Gestioname.Model", "FK_Pagos_Transacciones", "Transacciones")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Transacciones Transacciones
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Transacciones>("Gestioname.Model.FK_Pagos_Transacciones", "Transacciones").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Transacciones>("Gestioname.Model.FK_Pagos_Transacciones", "Transacciones").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Transacciones in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Transacciones> TransaccionesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Transacciones>("Gestioname.Model.FK_Pagos_Transacciones", "Transacciones");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Transacciones>("Gestioname.Model.FK_Pagos_Transacciones", "Transacciones", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Gestioname.Model.TiposTransacciones in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdTipoTransaccion
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Gestioname.Model", Name="TiposTransacciones")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TiposTransacciones : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TiposTransacciones object.
        /// </summary>
        /// <param name="idTipoTransaccion">Initial value of IdTipoTransaccion.</param>
        /// <param name="tipoTransacción">Initial value of TipoTransacción.</param>
        public static TiposTransacciones CreateTiposTransacciones(int idTipoTransaccion, string tipoTransacción)
        {
            TiposTransacciones tiposTransacciones = new TiposTransacciones();
            tiposTransacciones.IdTipoTransaccion = idTipoTransaccion;
            tiposTransacciones.TipoTransacción = tipoTransacción;
            return tiposTransacciones;
        }
        /// <summary>
        /// There are no comments for Property IdTipoTransaccion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoTransaccion
        {
            get
            {
                return this._IdTipoTransaccion;
            }
            set
            {
                this.OnIdTipoTransaccionChanging(value);
                this.ReportPropertyChanging("IdTipoTransaccion");
                this._IdTipoTransaccion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdTipoTransaccion");
                this.OnIdTipoTransaccionChanged();
            }
        }
        private int _IdTipoTransaccion;
        partial void OnIdTipoTransaccionChanging(int value);
        partial void OnIdTipoTransaccionChanged();
        /// <summary>
        /// There are no comments for Property TipoTransacción in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTransacción
        {
            get
            {
                return this._TipoTransacción;
            }
            set
            {
                this.OnTipoTransacciónChanging(value);
                this.ReportPropertyChanging("TipoTransacción");
                this._TipoTransacción = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("TipoTransacción");
                this.OnTipoTransacciónChanged();
            }
        }
        private string _TipoTransacción;
        partial void OnTipoTransacciónChanging(string value);
        partial void OnTipoTransacciónChanged();
        /// <summary>
        /// There are no comments for Property Descripcion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this._Descripcion;
            }
            set
            {
                this.OnDescripcionChanging(value);
                this.ReportPropertyChanging("Descripcion");
                this._Descripcion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Descripcion");
                this.OnDescripcionChanged();
            }
        }
        private string _Descripcion;
        partial void OnDescripcionChanging(string value);
        partial void OnDescripcionChanged();
        /// <summary>
        /// There are no comments for Transacciones in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Gestioname.Model", "FK_Transacciones_TiposTransacciones", "Transacciones")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Transacciones> Transacciones
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Transacciones>("Gestioname.Model.FK_Transacciones_TiposTransacciones", "Transacciones");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Transacciones>("Gestioname.Model.FK_Transacciones_TiposTransacciones", "Transacciones", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Gestioname.Model.Transacciones in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdTransaccion
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Gestioname.Model", Name="Transacciones")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Transacciones : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Transacciones object.
        /// </summary>
        /// <param name="idTransaccion">Initial value of IdTransaccion.</param>
        /// <param name="fecha">Initial value of Fecha.</param>
        /// <param name="monto">Initial value of Monto.</param>
        /// <param name="balance">Initial value of Balance.</param>
        public static Transacciones CreateTransacciones(int idTransaccion, global::System.DateTime fecha, string monto, string balance)
        {
            Transacciones transacciones = new Transacciones();
            transacciones.IdTransaccion = idTransaccion;
            transacciones.Fecha = fecha;
            transacciones.Monto = monto;
            transacciones.Balance = balance;
            return transacciones;
        }
        /// <summary>
        /// There are no comments for Property IdTransaccion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTransaccion
        {
            get
            {
                return this._IdTransaccion;
            }
            set
            {
                this.OnIdTransaccionChanging(value);
                this.ReportPropertyChanging("IdTransaccion");
                this._IdTransaccion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdTransaccion");
                this.OnIdTransaccionChanged();
            }
        }
        private int _IdTransaccion;
        partial void OnIdTransaccionChanging(int value);
        partial void OnIdTransaccionChanged();
        /// <summary>
        /// There are no comments for Property Fecha in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return this._Fecha;
            }
            set
            {
                this.OnFechaChanging(value);
                this.ReportPropertyChanging("Fecha");
                this._Fecha = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Fecha");
                this.OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
        /// <summary>
        /// There are no comments for Property Monto in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Monto
        {
            get
            {
                return this._Monto;
            }
            set
            {
                this.OnMontoChanging(value);
                this.ReportPropertyChanging("Monto");
                this._Monto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Monto");
                this.OnMontoChanged();
            }
        }
        private string _Monto;
        partial void OnMontoChanging(string value);
        partial void OnMontoChanged();
        /// <summary>
        /// There are no comments for Property Balance in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Balance
        {
            get
            {
                return this._Balance;
            }
            set
            {
                this.OnBalanceChanging(value);
                this.ReportPropertyChanging("Balance");
                this._Balance = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Balance");
                this.OnBalanceChanged();
            }
        }
        private string _Balance;
        partial void OnBalanceChanging(string value);
        partial void OnBalanceChanged();
        /// <summary>
        /// There are no comments for Property IdPago in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> IdPago
        {
            get
            {
                return this._IdPago;
            }
            set
            {
                this.OnIdPagoChanging(value);
                this.ReportPropertyChanging("IdPago");
                this._IdPago = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdPago");
                this.OnIdPagoChanged();
            }
        }
        private global::System.Nullable<int> _IdPago;
        partial void OnIdPagoChanging(global::System.Nullable<int> value);
        partial void OnIdPagoChanged();
        /// <summary>
        /// There are no comments for Cuentas in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Gestioname.Model", "FK_Transacciones_Cuentas", "Cuentas")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Cuentas Cuentas
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cuentas>("Gestioname.Model.FK_Transacciones_Cuentas", "Cuentas").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cuentas>("Gestioname.Model.FK_Transacciones_Cuentas", "Cuentas").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Cuentas in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Cuentas> CuentasReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cuentas>("Gestioname.Model.FK_Transacciones_Cuentas", "Cuentas");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Cuentas>("Gestioname.Model.FK_Transacciones_Cuentas", "Cuentas", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Pagos in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Gestioname.Model", "FK_Pagos_Transacciones", "Pagos")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Pagos> Pagos
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Pagos>("Gestioname.Model.FK_Pagos_Transacciones", "Pagos");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Pagos>("Gestioname.Model.FK_Pagos_Transacciones", "Pagos", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for TiposTransacciones in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Gestioname.Model", "FK_Transacciones_TiposTransacciones", "TiposTransacciones")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public TiposTransacciones TiposTransacciones
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TiposTransacciones>("Gestioname.Model.FK_Transacciones_TiposTransacciones", "TiposTransacciones").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TiposTransacciones>("Gestioname.Model.FK_Transacciones_TiposTransacciones", "TiposTransacciones").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for TiposTransacciones in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<TiposTransacciones> TiposTransaccionesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TiposTransacciones>("Gestioname.Model.FK_Transacciones_TiposTransacciones", "TiposTransacciones");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<TiposTransacciones>("Gestioname.Model.FK_Transacciones_TiposTransacciones", "TiposTransacciones", value);
                }
            }
        }
    }
}
