//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Gestioname.Infrastructure.Model", "FK_Cuentas_Clientes", "Clientes", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Gestioname.Infrastructure.Model.Cliente), "Cuentas", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gestioname.Infrastructure.Model.Cuenta))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Gestioname.Infrastructure.Model", "FK_Transacciones_Cuentas", "Cuentas", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gestioname.Infrastructure.Model.Cuenta), "Transacciones", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gestioname.Infrastructure.Model.Transaccion))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Gestioname.Infrastructure.Model", "FK_Pagos_Transacciones", "Transacciones", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gestioname.Infrastructure.Model.Transaccion), "Pagos", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gestioname.Infrastructure.Model.Pago))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Gestioname.Infrastructure.Model", "FK_Transacciones_TiposTransacciones", "TiposTransacciones", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gestioname.Infrastructure.Model.TipoTransaccion), "Transacciones", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gestioname.Infrastructure.Model.Transaccion))]

// Original file name:
// Generation date: 06/01/2009 03:15:37 p.m.
namespace Gestioname.Infrastructure.Model
{
    
    /// <summary>
    /// There are no comments for GestionameContext in the schema.
    /// </summary>
    public partial class GestionameContext : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new GestionameContext object using the connection string found in the 'GestionameContext' section of the application configuration file.
        /// </summary>
        public GestionameContext() : 
                base("name=GestionameContext", "GestionameContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GestionameContext object.
        /// </summary>
        public GestionameContext(string connectionString) : 
                base(connectionString, "GestionameContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GestionameContext object.
        /// </summary>
        public GestionameContext(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "GestionameContext")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for ClienteSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Cliente> ClienteSet
        {
            get
            {
                if ((this._ClienteSet == null))
                {
                    this._ClienteSet = base.CreateQuery<Cliente>("[ClienteSet]");
                }
                return this._ClienteSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Cliente> _ClienteSet;
        /// <summary>
        /// There are no comments for CuentaSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Cuenta> CuentaSet
        {
            get
            {
                if ((this._CuentaSet == null))
                {
                    this._CuentaSet = base.CreateQuery<Cuenta>("[CuentaSet]");
                }
                return this._CuentaSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Cuenta> _CuentaSet;
        /// <summary>
        /// There are no comments for PagoSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Pago> PagoSet
        {
            get
            {
                if ((this._PagoSet == null))
                {
                    this._PagoSet = base.CreateQuery<Pago>("[PagoSet]");
                }
                return this._PagoSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Pago> _PagoSet;
        /// <summary>
        /// There are no comments for TipoTransaccionSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TipoTransaccion> TipoTransaccionSet
        {
            get
            {
                if ((this._TipoTransaccionSet == null))
                {
                    this._TipoTransaccionSet = base.CreateQuery<TipoTransaccion>("[TipoTransaccionSet]");
                }
                return this._TipoTransaccionSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TipoTransaccion> _TipoTransaccionSet;
        /// <summary>
        /// There are no comments for TransaccionSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Transaccion> TransaccionSet
        {
            get
            {
                if ((this._TransaccionSet == null))
                {
                    this._TransaccionSet = base.CreateQuery<Transaccion>("[TransaccionSet]");
                }
                return this._TransaccionSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Transaccion> _TransaccionSet;
        /// <summary>
        /// There are no comments for ClienteSet in the schema.
        /// </summary>
        public void AddToClienteSet(Cliente cliente)
        {
            base.AddObject("ClienteSet", cliente);
        }
        /// <summary>
        /// There are no comments for CuentaSet in the schema.
        /// </summary>
        public void AddToCuentaSet(Cuenta cuenta)
        {
            base.AddObject("CuentaSet", cuenta);
        }
        /// <summary>
        /// There are no comments for PagoSet in the schema.
        /// </summary>
        public void AddToPagoSet(Pago pago)
        {
            base.AddObject("PagoSet", pago);
        }
        /// <summary>
        /// There are no comments for TipoTransaccionSet in the schema.
        /// </summary>
        public void AddToTipoTransaccionSet(TipoTransaccion tipoTransaccion)
        {
            base.AddObject("TipoTransaccionSet", tipoTransaccion);
        }
        /// <summary>
        /// There are no comments for TransaccionSet in the schema.
        /// </summary>
        public void AddToTransaccionSet(Transaccion transaccion)
        {
            base.AddObject("TransaccionSet", transaccion);
        }
    }
    /// <summary>
    /// There are no comments for Gestioname.Infrastructure.Model.Cliente in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdCliente
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Gestioname.Infrastructure.Model", Name="Cliente")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Cliente : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Cliente object.
        /// </summary>
        /// <param name="idCliente">Initial value of IdCliente.</param>
        /// <param name="codigo">Initial value of Codigo.</param>
        public static Cliente CreateCliente(int idCliente, string codigo)
        {
            Cliente cliente = new Cliente();
            cliente.IdCliente = idCliente;
            cliente.Codigo = codigo;
            return cliente;
        }
        /// <summary>
        /// There are no comments for Property IdCliente in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente
        {
            get
            {
                return this._IdCliente;
            }
            set
            {
                this.OnIdClienteChanging(value);
                this.ReportPropertyChanging("IdCliente");
                this._IdCliente = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdCliente");
                this.OnIdClienteChanged();
            }
        }
        private int _IdCliente;
        partial void OnIdClienteChanging(int value);
        partial void OnIdClienteChanged();
        /// <summary>
        /// There are no comments for Property Codigo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this._Codigo;
            }
            set
            {
                this.OnCodigoChanging(value);
                this.ReportPropertyChanging("Codigo");
                this._Codigo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Codigo");
                this.OnCodigoChanged();
            }
        }
        private string _Codigo;
        partial void OnCodigoChanging(string value);
        partial void OnCodigoChanged();
        /// <summary>
        /// There are no comments for Property RazonSocial in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial
        {
            get
            {
                return this._RazonSocial;
            }
            set
            {
                this.OnRazonSocialChanging(value);
                this.ReportPropertyChanging("RazonSocial");
                this._RazonSocial = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("RazonSocial");
                this.OnRazonSocialChanged();
            }
        }
        private string _RazonSocial;
        partial void OnRazonSocialChanging(string value);
        partial void OnRazonSocialChanged();
        /// <summary>
        /// There are no comments for Property Domicilio in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Domicilio
        {
            get
            {
                return this._Domicilio;
            }
            set
            {
                this.OnDomicilioChanging(value);
                this.ReportPropertyChanging("Domicilio");
                this._Domicilio = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Domicilio");
                this.OnDomicilioChanged();
            }
        }
        private string _Domicilio;
        partial void OnDomicilioChanging(string value);
        partial void OnDomicilioChanged();
        /// <summary>
        /// There are no comments for Property Localidad in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Localidad
        {
            get
            {
                return this._Localidad;
            }
            set
            {
                this.OnLocalidadChanging(value);
                this.ReportPropertyChanging("Localidad");
                this._Localidad = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Localidad");
                this.OnLocalidadChanged();
            }
        }
        private string _Localidad;
        partial void OnLocalidadChanging(string value);
        partial void OnLocalidadChanged();
        /// <summary>
        /// There are no comments for Property Provincia in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this._Provincia;
            }
            set
            {
                this.OnProvinciaChanging(value);
                this.ReportPropertyChanging("Provincia");
                this._Provincia = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Provincia");
                this.OnProvinciaChanged();
            }
        }
        private string _Provincia;
        partial void OnProvinciaChanging(string value);
        partial void OnProvinciaChanged();
        /// <summary>
        /// There are no comments for Property CUIT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CUIT
        {
            get
            {
                return this._CUIT;
            }
            set
            {
                this.OnCUITChanging(value);
                this.ReportPropertyChanging("CUIT");
                this._CUIT = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CUIT");
                this.OnCUITChanged();
            }
        }
        private string _CUIT;
        partial void OnCUITChanging(string value);
        partial void OnCUITChanged();
        /// <summary>
        /// There are no comments for Cuentas in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Gestioname.Infrastructure.Model", "FK_Cuentas_Clientes", "Cuentas")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Cuenta> Cuentas
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Cuenta>("Gestioname.Infrastructure.Model.FK_Cuentas_Clientes", "Cuentas");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Cuenta>("Gestioname.Infrastructure.Model.FK_Cuentas_Clientes", "Cuentas", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Gestioname.Infrastructure.Model.Cuenta in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdCuenta
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Gestioname.Infrastructure.Model", Name="Cuenta")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Cuenta : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Cuenta object.
        /// </summary>
        /// <param name="idCuenta">Initial value of IdCuenta.</param>
        /// <param name="balance">Initial value of Balance.</param>
        public static Cuenta CreateCuenta(int idCuenta, string balance)
        {
            Cuenta cuenta = new Cuenta();
            cuenta.IdCuenta = idCuenta;
            cuenta.Balance = balance;
            return cuenta;
        }
        /// <summary>
        /// There are no comments for Property IdCuenta in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCuenta
        {
            get
            {
                return this._IdCuenta;
            }
            set
            {
                this.OnIdCuentaChanging(value);
                this.ReportPropertyChanging("IdCuenta");
                this._IdCuenta = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdCuenta");
                this.OnIdCuentaChanged();
            }
        }
        private int _IdCuenta;
        partial void OnIdCuentaChanging(int value);
        partial void OnIdCuentaChanged();
        /// <summary>
        /// There are no comments for Property Balance in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Balance
        {
            get
            {
                return this._Balance;
            }
            set
            {
                this.OnBalanceChanging(value);
                this.ReportPropertyChanging("Balance");
                this._Balance = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Balance");
                this.OnBalanceChanged();
            }
        }
        private string _Balance;
        partial void OnBalanceChanging(string value);
        partial void OnBalanceChanged();
        /// <summary>
        /// There are no comments for Cliente in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Gestioname.Infrastructure.Model", "FK_Cuentas_Clientes", "Clientes")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente Cliente
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cliente>("Gestioname.Infrastructure.Model.FK_Cuentas_Clientes", "Clientes").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cliente>("Gestioname.Infrastructure.Model.FK_Cuentas_Clientes", "Clientes").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Cliente in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cliente>("Gestioname.Infrastructure.Model.FK_Cuentas_Clientes", "Clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Cliente>("Gestioname.Infrastructure.Model.FK_Cuentas_Clientes", "Clientes", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Transacciones in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Gestioname.Infrastructure.Model", "FK_Transacciones_Cuentas", "Transacciones")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Transaccion> Transacciones
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Transaccion>("Gestioname.Infrastructure.Model.FK_Transacciones_Cuentas", "Transacciones");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Transaccion>("Gestioname.Infrastructure.Model.FK_Transacciones_Cuentas", "Transacciones", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Gestioname.Infrastructure.Model.Pago in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdPago
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Gestioname.Infrastructure.Model", Name="Pago")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Pago : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Pago object.
        /// </summary>
        /// <param name="idPago">Initial value of IdPago.</param>
        /// <param name="tipoPago">Initial value of TipoPago.</param>
        /// <param name="monto">Initial value of Monto.</param>
        public static Pago CreatePago(int idPago, string tipoPago, string monto)
        {
            Pago pago = new Pago();
            pago.IdPago = idPago;
            pago.TipoPago = tipoPago;
            pago.Monto = monto;
            return pago;
        }
        /// <summary>
        /// There are no comments for Property IdPago in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPago
        {
            get
            {
                return this._IdPago;
            }
            set
            {
                this.OnIdPagoChanging(value);
                this.ReportPropertyChanging("IdPago");
                this._IdPago = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdPago");
                this.OnIdPagoChanged();
            }
        }
        private int _IdPago;
        partial void OnIdPagoChanging(int value);
        partial void OnIdPagoChanged();
        /// <summary>
        /// There are no comments for Property TipoPago in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPago
        {
            get
            {
                return this._TipoPago;
            }
            set
            {
                this.OnTipoPagoChanging(value);
                this.ReportPropertyChanging("TipoPago");
                this._TipoPago = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("TipoPago");
                this.OnTipoPagoChanged();
            }
        }
        private string _TipoPago;
        partial void OnTipoPagoChanging(string value);
        partial void OnTipoPagoChanged();
        /// <summary>
        /// There are no comments for Property Monto in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Monto
        {
            get
            {
                return this._Monto;
            }
            set
            {
                this.OnMontoChanging(value);
                this.ReportPropertyChanging("Monto");
                this._Monto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Monto");
                this.OnMontoChanged();
            }
        }
        private string _Monto;
        partial void OnMontoChanging(string value);
        partial void OnMontoChanged();
        /// <summary>
        /// There are no comments for Property NumeroCheque in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCheque
        {
            get
            {
                return this._NumeroCheque;
            }
            set
            {
                this.OnNumeroChequeChanging(value);
                this.ReportPropertyChanging("NumeroCheque");
                this._NumeroCheque = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NumeroCheque");
                this.OnNumeroChequeChanged();
            }
        }
        private string _NumeroCheque;
        partial void OnNumeroChequeChanging(string value);
        partial void OnNumeroChequeChanged();
        /// <summary>
        /// There are no comments for Property Banco in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Banco
        {
            get
            {
                return this._Banco;
            }
            set
            {
                this.OnBancoChanging(value);
                this.ReportPropertyChanging("Banco");
                this._Banco = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Banco");
                this.OnBancoChanged();
            }
        }
        private string _Banco;
        partial void OnBancoChanging(string value);
        partial void OnBancoChanged();
        /// <summary>
        /// There are no comments for Property Fecha in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return this._Fecha;
            }
            set
            {
                this.OnFechaChanging(value);
                this.ReportPropertyChanging("Fecha");
                this._Fecha = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Fecha");
                this.OnFechaChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
        /// <summary>
        /// There are no comments for Transaccion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Gestioname.Infrastructure.Model", "FK_Pagos_Transacciones", "Transacciones")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Transaccion Transaccion
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Transaccion>("Gestioname.Infrastructure.Model.FK_Pagos_Transacciones", "Transacciones").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Transaccion>("Gestioname.Infrastructure.Model.FK_Pagos_Transacciones", "Transacciones").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Transaccion in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Transaccion> TransaccionReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Transaccion>("Gestioname.Infrastructure.Model.FK_Pagos_Transacciones", "Transacciones");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Transaccion>("Gestioname.Infrastructure.Model.FK_Pagos_Transacciones", "Transacciones", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Gestioname.Infrastructure.Model.TipoTransaccion in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdTipoTransaccion
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Gestioname.Infrastructure.Model", Name="TipoTransaccion")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TipoTransaccion : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TipoTransaccion object.
        /// </summary>
        /// <param name="idTipoTransaccion">Initial value of IdTipoTransaccion.</param>
        /// <param name="tipoTransacción">Initial value of TipoTransacción.</param>
        public static TipoTransaccion CreateTipoTransaccion(int idTipoTransaccion, string tipoTransacción)
        {
            TipoTransaccion tipoTransaccion = new TipoTransaccion();
            tipoTransaccion.IdTipoTransaccion = idTipoTransaccion;
            tipoTransaccion.TipoTransacción = tipoTransacción;
            return tipoTransaccion;
        }
        /// <summary>
        /// There are no comments for Property IdTipoTransaccion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoTransaccion
        {
            get
            {
                return this._IdTipoTransaccion;
            }
            set
            {
                this.OnIdTipoTransaccionChanging(value);
                this.ReportPropertyChanging("IdTipoTransaccion");
                this._IdTipoTransaccion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdTipoTransaccion");
                this.OnIdTipoTransaccionChanged();
            }
        }
        private int _IdTipoTransaccion;
        partial void OnIdTipoTransaccionChanging(int value);
        partial void OnIdTipoTransaccionChanged();
        /// <summary>
        /// There are no comments for Property TipoTransacción in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTransacción
        {
            get
            {
                return this._TipoTransacción;
            }
            set
            {
                this.OnTipoTransacciónChanging(value);
                this.ReportPropertyChanging("TipoTransacción");
                this._TipoTransacción = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("TipoTransacción");
                this.OnTipoTransacciónChanged();
            }
        }
        private string _TipoTransacción;
        partial void OnTipoTransacciónChanging(string value);
        partial void OnTipoTransacciónChanged();
        /// <summary>
        /// There are no comments for Property Descripcion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this._Descripcion;
            }
            set
            {
                this.OnDescripcionChanging(value);
                this.ReportPropertyChanging("Descripcion");
                this._Descripcion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Descripcion");
                this.OnDescripcionChanged();
            }
        }
        private string _Descripcion;
        partial void OnDescripcionChanging(string value);
        partial void OnDescripcionChanged();
        /// <summary>
        /// There are no comments for Transacciones in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Gestioname.Infrastructure.Model", "FK_Transacciones_TiposTransacciones", "Transacciones")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Transaccion> Transacciones
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Transaccion>("Gestioname.Infrastructure.Model.FK_Transacciones_TiposTransacciones", "Transacciones");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Transaccion>("Gestioname.Infrastructure.Model.FK_Transacciones_TiposTransacciones", "Transacciones", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Gestioname.Infrastructure.Model.Transaccion in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdTransaccion
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Gestioname.Infrastructure.Model", Name="Transaccion")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Transaccion : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Transaccion object.
        /// </summary>
        /// <param name="idTransaccion">Initial value of IdTransaccion.</param>
        /// <param name="fecha">Initial value of Fecha.</param>
        /// <param name="monto">Initial value of Monto.</param>
        /// <param name="balance">Initial value of Balance.</param>
        public static Transaccion CreateTransaccion(int idTransaccion, global::System.DateTime fecha, string monto, string balance)
        {
            Transaccion transaccion = new Transaccion();
            transaccion.IdTransaccion = idTransaccion;
            transaccion.Fecha = fecha;
            transaccion.Monto = monto;
            transaccion.Balance = balance;
            return transaccion;
        }
        /// <summary>
        /// There are no comments for Property IdTransaccion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTransaccion
        {
            get
            {
                return this._IdTransaccion;
            }
            set
            {
                this.OnIdTransaccionChanging(value);
                this.ReportPropertyChanging("IdTransaccion");
                this._IdTransaccion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdTransaccion");
                this.OnIdTransaccionChanged();
            }
        }
        private int _IdTransaccion;
        partial void OnIdTransaccionChanging(int value);
        partial void OnIdTransaccionChanged();
        /// <summary>
        /// There are no comments for Property Fecha in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return this._Fecha;
            }
            set
            {
                this.OnFechaChanging(value);
                this.ReportPropertyChanging("Fecha");
                this._Fecha = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Fecha");
                this.OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
        /// <summary>
        /// There are no comments for Property Monto in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Monto
        {
            get
            {
                return this._Monto;
            }
            set
            {
                this.OnMontoChanging(value);
                this.ReportPropertyChanging("Monto");
                this._Monto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Monto");
                this.OnMontoChanged();
            }
        }
        private string _Monto;
        partial void OnMontoChanging(string value);
        partial void OnMontoChanged();
        /// <summary>
        /// There are no comments for Property Balance in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Balance
        {
            get
            {
                return this._Balance;
            }
            set
            {
                this.OnBalanceChanging(value);
                this.ReportPropertyChanging("Balance");
                this._Balance = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Balance");
                this.OnBalanceChanged();
            }
        }
        private string _Balance;
        partial void OnBalanceChanging(string value);
        partial void OnBalanceChanged();
        /// <summary>
        /// There are no comments for Property IdPago in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> IdPago
        {
            get
            {
                return this._IdPago;
            }
            set
            {
                this.OnIdPagoChanging(value);
                this.ReportPropertyChanging("IdPago");
                this._IdPago = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdPago");
                this.OnIdPagoChanged();
            }
        }
        private global::System.Nullable<int> _IdPago;
        partial void OnIdPagoChanging(global::System.Nullable<int> value);
        partial void OnIdPagoChanged();
        /// <summary>
        /// There are no comments for Cuenta in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Gestioname.Infrastructure.Model", "FK_Transacciones_Cuentas", "Cuentas")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Cuenta Cuenta
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cuenta>("Gestioname.Infrastructure.Model.FK_Transacciones_Cuentas", "Cuentas").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cuenta>("Gestioname.Infrastructure.Model.FK_Transacciones_Cuentas", "Cuentas").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Cuenta in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Cuenta> CuentaReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cuenta>("Gestioname.Infrastructure.Model.FK_Transacciones_Cuentas", "Cuentas");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Cuenta>("Gestioname.Infrastructure.Model.FK_Transacciones_Cuentas", "Cuentas", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Pagos in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Gestioname.Infrastructure.Model", "FK_Pagos_Transacciones", "Pagos")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Pago> Pagos
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Pago>("Gestioname.Infrastructure.Model.FK_Pagos_Transacciones", "Pagos");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Pago>("Gestioname.Infrastructure.Model.FK_Pagos_Transacciones", "Pagos", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for TiposTransacciones in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Gestioname.Infrastructure.Model", "FK_Transacciones_TiposTransacciones", "TiposTransacciones")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public TipoTransaccion TiposTransacciones
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TipoTransaccion>("Gestioname.Infrastructure.Model.FK_Transacciones_TiposTransacciones", "TiposTransacciones").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TipoTransaccion>("Gestioname.Infrastructure.Model.FK_Transacciones_TiposTransacciones", "TiposTransacciones").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for TiposTransacciones in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<TipoTransaccion> TiposTransaccionesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TipoTransaccion>("Gestioname.Infrastructure.Model.FK_Transacciones_TiposTransacciones", "TiposTransacciones");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<TipoTransaccion>("Gestioname.Infrastructure.Model.FK_Transacciones_TiposTransacciones", "TiposTransacciones", value);
                }
            }
        }
    }
}
